### ISSUE TITLE
Suggestions for Enhancements to Discord Messenger

### ISSUE THREAD

**Issue by RaulKong898** [DiscordMessenger/dm#103]
Dear Discord Messenger Development Team,

I hope this message finds you well. I am writing to share some suggestions for enhancing Discord Messenger, which I believe would significantly improve the user experience.

1. **Installer for Discord Messenger**:
   - **Setup.exe**: Please add an installer for Discord Messenger to create a `setup.exe` file. This would simplify the installation process for users.
   - **Background Running**: Implement an option in the installer to allow Discord Messenger to run in the background. Users should have the ability to minimize the app to the system tray, keeping it active even when the main window is closed using the 'X' button.

2. **Server Selection Navigation Issue**:
   - **Scroll Functionality**: There's a navigation issue where users cannot easily scroll through and select different servers if they have a large number of them. Improving this functionality would enhance usability, particularly for power users managing multiple servers.

3. **Compatibility with Windows XP x64 and All x64 Windows Versions**:
   - **Support for Older Systems**: Develop a version of Discord Messenger compatible with Windows XP x64. Ensuring compatibility with all x64 versions of Windows would make the app accessible to a broader audience, including those using older systems.

4. **Auto-Start with Windows**:
   - **Startup Option**: Provide an option to launch Discord Messenger automatically when Windows starts. This feature can be integrated into the settings, allowing users to enable or disable it as per their preference.

I believe these enhancements will make Discord Messenger more user-friendly and accessible. Thank you for considering these suggestions. I look forward to seeing these improvements in future releases.

Best regards,
Kong

**Comment by 0x5066** [comment]
This reads like ChatGPT wrote this...

**Comment by RaulKong898** [comment]
> This reads like ChatGPT wrote this...

Yes, but I said what to write. I am not very good in English and I said to help me.

**Comment by RF7391** [comment]
Tf you mean make it x64 compatible, what abt x32 makes it unusable

**Comment by iProgramMC** [comment]
Hello. This appears to be written by AI, therefore I can't take you seriously, but I'll try.

* Setup is already incredibly easy: download and extract the archive from releases. Then open the executable tentatively named "DiscordMessenger.exe". If you want, you can drag this into the program files directory and create a shortcut on the desktop linking there.
* Discord Messenger has no notification support currently, so running in the background would be completely pointless.
* On Windows versions older than 10, you can click the server list to start scrolling there. I acknowledge that this isn't very user friendly, so I'm thinking I can make a server selector icon, which shows all servers as a list, or a scroll bar option, or both.
* 32-bit x86 builds of Discord Messenger are compatible with 64-bit Windows versions.
* Automatic startup is pointless because, again, Discord Messenger has no notification support yet.

**Comment by iProgramMC** [comment]
> Yes, but I said what to write. I am not very good in English and I said to help me.

You can write in your broken English, or in your native language, I can ask google to translate it for me.
