### ISSUE TITLE
More simpler directions?

### ISSUE THREAD

**Issue by Alex-Toucan** [DiscordMessenger/dm#67]
I'm using a Windows XP Professional x64 Edition and am new to compiling using either method. These instructions aren't clear.

For the Visual Studio directions:
* Step 4, could not find the `DiscordMessenger.sln` file anywhere in the zip file.

For the MiNGW directions:
* Step 3, you cannot find the `PATH` variable.
* Step 4, there is no `make` command recognized.

**Comment by Alex-Toucan** [comment]
@iProgramMC There is no .sln file in either ZIP folder listed in https://github.com/DiscordMessenger/dm/releases.

**Comment by iProgramMC** [comment]
> [@iProgramMC](https://github.com/iProgramMC) There is no .sln file in either ZIP folder listed in https://github.com/DiscordMessenger/dm/releases.

Because those ZIP files do not contain the source code.

You need to check out the source and submodules using git. It doesn't look like I specified how to checkout submodules, mistake on my part.

To checkout submodules after cloning the project (`git clone (this project's URL)`), you need to run `git submodule update --init` before following any build step. For whatever cringey reason GitHub doesn't automatically clone submodules (or even give you indications as to how to do that!) when you click "download as zip".

Alternatively you can download as zip, and then download https://github.com/nothings/stb, https://github.com/DiscordMessenger/mwas, and https://github.com/DiscordMessenger/iprogsthreads, and extract them into their corresponding place in the deps/ folder according to the .gitmodules file.

> There is only `TEMP` or `TMP` in the environment variables.

No, there isn't. Otherwise you wouldn't be able to run any command in the command prompt outside of CMD built-in ones or the ones in your working directory. Open `sysdm.cpl`, go to the advanced tab, and click *Environment Variables*.
