### ISSUE TITLE
Why not just have a toggle for dark mode?

### ISSUE THREAD

**Issue by K4sum1** [DiscordMessenger/dm#71]
Why restrict it to modern systems and hook complex APIs? Why not just have a dark mode checkbox in settings?

**Comment by iProgramMC** [comment]
It occurs to me that you don't understand how Win32 works. Windows was never conceived with a dark mode in mind, therefore common controls (scroll bars, edit boxes, etc, of which we use plenty) can't be styled a different way from the one the active Windows theme allows.

There's no way to "just" add a check box for dark mode, if I _only_ did that I'd have a dud that does nothing.

For Windows 7 and below you can just make a dark classic theme if you so desire.

**Comment by K4sum1** [comment]
I guess that makes sense as you aren't using a toolkit. However I see options for adjusting Message Style and there are Flat Color settings. Are these just taken from different colors of the current theme?

**Comment by iProgramMC** [comment]
These are just taken from different colors of the current theme.

I _could_ restyle the custom controls indeed, but I feel that it would look VERY out of place compared to the custom controls. Here's an example where I invert the colors of all the custom stuff (except profile pictures), and the main window's background:

![image](https://github.com/DiscordMessenger/dm/assets/17717494/c4dc9253-1c05-4cc8-aeae-4600f71ba7b9)

**Comment by iProgramMC** [comment]
Checked out Abaddon's screenshots (you mentioned it in another issue), it looks nice but yeah I'm not using a toolkit such as Qt or GTK so I'm unable to use their dark mode features.

**Comment by K4sum1** [comment]
Yeah, that makes sense.

**Comment by RF7391** [comment]
Tbh if ppl want a dark theme they should use an msstyle to apply it instead of asking for one in dm

**Comment by K4sum1** [comment]
> For Windows 7 and below you can just make a dark classic theme if you so desire.

:​troll​:
![windows_8 1_dark_classic_theme](https://github.com/DiscordMessenger/dm/assets/77039240/88c66b59-4e0d-466d-8ac0-ac3ca2ca8fd0)

**Comment by iProgramMC** [comment]
That's pretty cool, how did you do that?

**Comment by K4sum1** [comment]
The most jank way possible but it works really well.
https://files.catbox.moe/pdns19.7z

When WinClassic is back online I also have the 7 network pane working too, should be one of the newest posts here.
https://winclassic.net/thread/2222/windows-van-dll-running-21h2

**Comment by OrthodoxWindows** [comment]
> It occurs to me that you don't understand how Win32 works. Windows was never conceived with a dark mode in mind, therefore common controls (scroll bars, edit boxes, etc, of which we use plenty) can't be styled a different way from the one the active Windows theme allows.
> 
> There's no way to "just" add a check box for dark mode, if I _only_ did that I'd have a dud that does nothing.
> 
> For Windows 7 and below you can just make a dark classic theme if you so desire.

Win32 supports the dark theme very well, but Microsoft is doing everything to prevent this. It would be enough to use another visual style (like in Windows XP, with the Luna, Olive and Metallic themes) to have a dark mode. This is what the Rectify11 team does. But Microsoft persists in advising the use (to add compatibility with an incomplete dark theme) of complicated APIs that are unsuitable for older applications.
Fortunately, it is possible to use third-party visual styles, or the classic theme (because yes, as K4sum1 showed, it is possible to use the classic theme in versions later than Windows 7).

**Comment by iProgramMC** [comment]
> Win32 supports the dark theme very well,

No, it doesn't support *the* dark theme. It supports any kind of theme you throw at it.

I don't understand why Microsoft is hiding theme settings so hard. "Muh compatibility" is not a reason.

Additionally, the only reason Win32 even has dark mode interfaces at all is because they don't want to rewrite Windows Explorer using the newest WinUI APIs. If they did that, we probably wouldn't have any kind of dark mode API at all.

Because they only added a "dark mode" for Windows Explorer, we would have to do some ungodly hacks to get dark mode in Discord Messenger. And it wouldn't be complete. For example, whatever we do, I don't think we can make `DrawEdge` use dark theme colors.

Not only would we need to apply a custom theme to all common controls, we'd also need to hook into GetSysColor, which is super duper nasty.

All in all, Microsoft and its Win32 dark mode support sucks. They claim it's for "compatibility", but really it's just an excuse to get you to use their latest APIs.

**Comment by OrthodoxWindows** [comment]
> > Win32 supports the dark theme very well,
> 
> No, it doesn't support _the_ dark theme. It supports any kind of theme you throw at it.
> 
> I don't understand why Microsoft is hiding theme settings so hard. "Muh compatibility" is not a reason.
> 
> Additionally, the only reason Win32 even has dark mode interfaces at all is because they don't want to rewrite Windows Explorer using the newest WinUI APIs. If they did that, we probably wouldn't have any kind of dark mode API at all.
> 
> Because they only added a "dark mode" for Windows Explorer, we would have to do some ungodly hacks to get dark mode in Discord Messenger. And it wouldn't be complete. For example, whatever we do, I don't think we can make `DrawEdge` use dark theme colors.
> 
> Not only would we need to apply a custom theme to all common controls, we'd also need to hook into GetSysColor, which is super duper nasty.
> 
> All in all, Microsoft and its Win32 dark mode support sucks. They claim it's for "compatibility", but really it's just an excuse to get you to use their latest APIs.

I totally agree.
In any case, Microsoft would only need an "aerodark.msstyle" to have a perfect dark theme. It is therefore clear that Microsoft deliberately does not want this.

**Comment by K4sum1** [comment]
I noticed HTTP Downloader doesn't seem to have any big toolkit and I can adjust the color for basically everything in it. Whatever it uses is also compatible with XP too. Maybe you could give it a look?

https://github.com/erickutcher/httpdownloader/releases

**Comment by iProgramMC** [comment]
That about dialog box is clearly not from XP, it looks like you're using some kind of realistic XP mod such as Windows eXPerience. Try again.

The gist of it is this: If you want dark mode, set your system to dark and enjoy. Discord Messenger will happily drum along with whatever theme you throw at it.

Here's a demo:
![VirtualBox_Windows XP_22_07_2024_23_07_32](https://github.com/user-attachments/assets/51f360ce-9e20-49de-89be-e339fc1615a6)

**Comment by K4sum1** [comment]
> That about dialog box is clearly not from XP, it looks like you're using some kind of realistic XP mod such as Windows eXPerience. Try again.

![ScreenShot_20240722193342](https://github.com/user-attachments/assets/177d2326-92ce-4166-a542-ef620b9ee331)
