### ISSUE TITLE
What is the point of having both MinGW and MSVC downloads?

### ISSUE THREAD

**Issue by K4sum1** [DiscordMessenger/dm#72]
Looking at them, the MinGW version is more compatible and a smaller file size. Therefore it seems like it's overall better. Why offer a MSVC build?

**Comment by iProgramMC** [comment]
1. Not an issue.
2. The MSVC executable is actually _smaller_ than MinGW executable. The only reason it's so large is because I include a 25MB pdb file to allow myself to debug crashes on that version from the event viewer log, in case they ever happen.
3. I offer an MSVC build also because it's only logical. I bundle a VS2022 project therefore I would want to also provide the build artifacts for it.

Also, for these kinds of questions I'd actually appreciate contacting me by email (iprogramincpp at Gmail), so as to not clutter the issues list.

**Comment by K4sum1** [comment]
> Also, for these kinds of questions I'd actually appreciate contacting me by email (iprogramincpp at Gmail), so as to not clutter the issues list.

I was thinking of trying to ask on Discord first, but I couldn't find an invite or server anywhere, and email just always ends up unanswered or in spam every time.

**Comment by iProgramMC** [comment]
No, it doesn't, I check my mail pretty much every day.

**Comment by K4sum1** [comment]
I guess. I just always have that happen, so I didn't even consider it.
